### ISSUE TITLE
Latitude longitude mapbox

### ISSUE THREAD

**Issue by Kevin-com** [rainviewer/rainviewer-api-example#1]
Hello,

first of all, thank you for this! Great tool.

I have a question sir,... Is there a way to enter the latitude longitude of a map to start in the code? Maybe i'm blind i can't find it.

Thank you very much for your answer.
Greetings from Belgium.

**Comment by luckyalvy** [comment]
Hi Kevin! 
Thanks for your question.

The first line of Javascript code is that line with coordinates for the map center.

`var map = L.map('mapid').setView([40.633333, -73.716667], 7);`

40.633333 - latitude, -73.716667 - longitude. 7 - zoom level.

I hope that helps
